---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-demo
  template:
    metadata:
      labels:
        app: deployment-demo
    spec:
      containers:
      - name: deployment-demo
        image: denisjd/deployment-demo-app
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: deployment-demo-svc
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    app: deployment-demo
